
import java.awt.Point;
import java.io.File;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Cristina
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private int numVentanas=0;
    private int nSegmentos = 35;
    private int pixeles = 64;
    private int wxh = 2240;
    SelectDataToSegment pixelesFrame = new SelectDataToSegment();
    
    public Escritorio() {
        initComponents();
        jDesktopPane1.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuPixeles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");

        menuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        menuInicio.add(menuAbrir);

        jMenuBar1.add(menuInicio);

        menuEditar.setText("Editar");

        menuPixeles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPixeles.setText("Seleccionar pixeles");
        menuPixeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPixelesActionPerformed(evt);
            }
        });
        menuEditar.add(menuPixeles);

        jMenuBar1.add(menuEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogTitle("Seleccionar imagen a mapear");
        
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Ficheros png","png"));
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Ficheros gif","gif"));
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Ficheros jpg, jpeg","jpg","jpeg"));

        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            
            File f = fc.getSelectedFile();
            String path = fc.getSelectedFile().getAbsolutePath();
            String nombre = fc.getSelectedFile().getName();
            System.out.println(nombre);
            
            try{
                GeneraVentana(f);  
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(jDesktopPane1,"Imagen no válida",
                            "Fallo al abrir",ERROR_MESSAGE);
            }
     
        }
        
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void GeneraVentana (File f){
        //Llamamos a los get de pixeles y nSegmentos para actualizar las variables
        pixeles = pixelesFrame.getPixeles();
        nSegmentos = pixelesFrame.getnSegmentos();
        wxh = pixelesFrame.getTamaño();
        System.out.println("Tamaño de imagen supuesto= " + wxh );
        //COMPROBAR EL TAMAÑO DE LA IMAGEN
        Imagen img = new Imagen(f);
        SegmentationInterface ventana = new SegmentationInterface(img,nSegmentos,wxh);
        numVentanas++;
        jDesktopPane1.add(ventana);
        ventana.setLocation(new Point(numVentanas*20,numVentanas*20));
        ventana.setResizable(true);
        ventana.setClosable(true);
        ventana.setTitle(f.getName());
        ventana.setVisible(true);
    }
        
    private void menuPixelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPixelesActionPerformed
        pixelesFrame.setLocation(new Point(100,100));
        pixelesFrame.setVisible(true);
        //Las variables de pixeles y nSegmento se actualizan antes de crear la ventana
        
    }//GEN-LAST:event_menuPixelesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        confirmacionSalida();
    }//GEN-LAST:event_formWindowClosing
    
    public void confirmacionSalida(){
        int res = JOptionPane.showConfirmDialog(null,"¿Estas seguro "
                + "que quieres salir de la aplicación?","salir", JOptionPane.YES_NO_OPTION);
        if(res == JOptionPane.YES_OPTION){
                System.exit(0); 
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuPixeles;
    // End of variables declaration//GEN-END:variables
}
